#!/usr/bin/env bash
set -euo pipefail

# ─── Config ───────────────────────────────────────────────────────────
CONTRACTS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_DIR="$(cd "$CONTRACTS_DIR/.." && pwd)"
OUT_DIR="$CONTRACTS_DIR/out"
OUTPUT_FILE="$ROOT_DIR/src/lib/guestbook-abi.ts"

CHAIN_ID="${1:-31337}"

# ─── Helpers ──────────────────────────────────────────────────────────
get_abi() {
  local contract_name="$1"
  local artifact="$OUT_DIR/${contract_name}.sol/${contract_name}.json"
  if [[ ! -f "$artifact" ]]; then
    echo "ERROR: Artifact not found: $artifact" >&2
    echo "       Run 'forge build' first." >&2
    exit 1
  fi
  jq '.abi' "$artifact"
}

get_address() {
  local contract_name="$1"
  local index="$2"
  local broadcast="$CONTRACTS_DIR/broadcast/Deploy.s.sol/${CHAIN_ID}/run-latest.json"
  if [[ ! -f "$broadcast" ]]; then
    echo "ERROR: Broadcast not found: $broadcast" >&2
    echo "       Deploy the contracts first." >&2
    exit 1
  fi
  jq -r ".transactions[$index].contractAddress" "$broadcast"
}

# ─── Extract ──────────────────────────────────────────────────────────
echo "📦 Syncing from chain $CHAIN_ID..."

GUESTBOOK_ABI=$(get_abi "Guestbook")
VISITOR_PASS_ABI=$(get_abi "VisitorPass")
GUESTBOOK_ADDR=$(get_address "Guestbook" 0)
VISITOR_PASS_ADDR=$(get_address "VisitorPass" 1)

echo "   Guestbook:   $GUESTBOOK_ADDR"
echo "   VisitorPass:  $VISITOR_PASS_ADDR"

# ─── Generate TypeScript ──────────────────────────────────────────────
cat > "$OUTPUT_FILE" <<EOF
// Auto-generated by contracts/scripts/sync-frontend.sh — do not edit manually
export const GUESTBOOK_ABI = ${GUESTBOOK_ABI} as const;

export const VISITOR_PASS_ABI = ${VISITOR_PASS_ABI} as const;

export const GUESTBOOK_ADDRESS = "${GUESTBOOK_ADDR}";
export const VISITOR_PASS_ADDRESS = "${VISITOR_PASS_ADDR}";
export const CHAIN_ID = ${CHAIN_ID};
EOF

echo "✅ Generated $OUTPUT_FILE"
